connect_db/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView
from hospital.views import patient, doctor, login

urlpatterns = [
    #path('', RedirectView.as_view(url='/login/', permanent=True), name='index'),
    # 其他URL模式
    path("admin/", admin.site.urls),
    path("login/", login.login),
    path("enroll/", login.enroll),
    path("logout/", login.logout),
    
    path("patient/home/", patient.home),
    path("patient/register/", patient.register),
    path("patient/register/appoint/<int:doctor_id>/", patient.register_appoint),
    path("patient/register/success/", patient.register_sucess),
    path("patient/register/appoint/", patient.register_appoint_test),
    path("patient/registrations/", patient.registrations),
    path("patient/cancel_registration/<int:registration_id>/", patient.cancel_registration),
    path("patient/personnel/", patient.personnel),
    path("patient/profile/<int:doctor_id>/", patient.profile),
    path('patient/medical_record/<int:registration_id>/', patient.medical_record),
    path('patient/personal/', patient.personal),
    path("mytest/", patient.mytest),

    path('doctor/home/', doctor.home),
    path('doctor/registrations/', doctor.registrations),
    path('doctor/medical_record/<int:registration_id>/', doctor.medical_record),
    path('doctor/accept/<int:registration_id>/', doctor.accept),
    path('doctor/finish/<int:registration_id>/', doctor.finish),
    path('doctor/medicine/', doctor.medicine),
    path('doctor/personal/', doctor.personal),
]

hospital/models.py
from django.db import models

class Patient(models.Model):
    '''病人'''
    name = models.CharField(verbose_name='姓名', max_length = 20)
    age = models.IntegerField(verbose_name='年龄', null=True, blank=True)
    username = models.CharField(verbose_name='用户名', max_length = 20, unique=True)
    password = models.CharField(verbose_name='密码', max_length = 20)
    GENDER_CHOICES = [
        (0, '男'),
        (1, '女'),
    ]
    gender = models.SmallIntegerField(verbose_name='性别', choices=GENDER_CHOICES, null=True, blank=True)

class Department(models.Model):
    '''科室'''
    name = models.CharField(verbose_name='科室名', max_length = 30)
    room_number = models.CharField(verbose_name='房间号', max_length = 20)

class Doctor(models.Model):
    '''医生'''
    name = models.CharField(verbose_name='姓名', max_length = 20)
    username = models.CharField(verbose_name='用户名', max_length = 20, unique=True)
    password = models.CharField(verbose_name='密码', max_length = 20)
    title = models.CharField(verbose_name='职称', max_length = 20)
    dept = models.ForeignKey(Department, verbose_name='科室', on_delete=models.CASCADE)
    profile = models.CharField(verbose_name='简介', max_length = 200)


class Registration(models.Model):
    '''挂号记录'''

    # class Meta:
    #     verbose_name = '挂号记录'
    #     verbose_name_plural = '挂号记录'

    STATUS_CHOICES = [
        (0, '已挂号'),
        (1, '已取消'),
        (2, '就诊中'),
        (3, '就诊结束'),
    ]

    PERIOD_CHOICES = [
        (0, '8:00-10:00'),
        (1, '10:00-12:00'),
        (2, '14:00-16:00'),
        (3, '16:00-18:00'),
    ]

    doctor = models.ForeignKey(Doctor, verbose_name='医生', on_delete=models.CASCADE, related_name='registrations')
    patient = models.ForeignKey(Patient, verbose_name='患者', on_delete=models.CASCADE, related_name='appointments')
    registration_time = models.DateTimeField(verbose_name='挂号时间')
    period = models.SmallIntegerField(verbose_name='挂号时段', choices=PERIOD_CHOICES)
    status = models.SmallIntegerField(verbose_name='状态', choices=STATUS_CHOICES)

class MedicalRecord(models.Model):
    '''病历'''
    symptom = models.CharField(verbose_name='症状', max_length = 2000)
    diagnosis = models.CharField(verbose_name='诊断结果', max_length = 2000)
    solution = models.CharField(verbose_name='治疗方案', max_length = 2000)
    registration = models.ForeignKey(Registration, verbose_name='预约信息', on_delete=models.CASCADE)


class Medicine(models.Model):
    '''药物'''
    TYPE_CHOICES = [
        (0, '中药'),
        (1, '西药'),
    ]

    name = models.CharField(verbose_name='名称', max_length = 100)
    type = models.SmallIntegerField(verbose_name='类型', choices=TYPE_CHOICES)
    producer = models.CharField(verbose_name='生产厂商', max_length = 100)
    price = models.DecimalField(verbose_name='价格', max_digits=5, decimal_places=2)

hospital/views/doctor.py
from django.shortcuts import render, redirect, get_object_or_404
from hospital.models import *
from django import forms
from django.core.paginator import Paginator

def home(request):
    return render(request, 'doctor/home.html')

def registrations(request):
    doctor_id = request.session.get('info')['id']
    doctor = Doctor.objects.get(id=doctor_id)
    registrations = Registration.objects.filter(doctor=doctor).order_by('registration_time', 'period')


    # 分页
    paginator = Paginator(registrations, 5)
    page_number = request.GET.get('page')
    registrations = paginator.get_page(page_number)

    return render(request, 'doctor/registrations.html', {'registrations': registrations})

class MedicalRecordForm(forms.ModelForm):
    class Meta:
        model = MedicalRecord
        exclude = ['registration']

def medical_record(request, registration_id):
    registration = get_object_or_404(Registration, pk=registration_id)
    
    try:
        medical_record = MedicalRecord.objects.get(registration=registration)
    except MedicalRecord.DoesNotExist:
        medical_record = None

    patient = registration.patient

    if request.method == 'GET':
        if medical_record == None:
            form = None
        else:
            form = MedicalRecordForm(instance=medical_record)
        return render(request, 'doctor/medical_record.html', {'form': form, 'patient': patient})

    form = MedicalRecordForm(request.POST, instance=medical_record)
    if form.is_valid():
        medical_record = form.save(commit=False)
        medical_record.registration = registration
        medical_record.save()
    return render(request, 'doctor/medical_record.html', {'form': form, 'patient': patient})
    
def accept(request, registration_id):
    registration = get_object_or_404(Registration, pk=registration_id)
    registration.status = 2
    registration.save()
    print('accept', registration_id)
    return redirect('/doctor/registrations')

def finish(request, registration_id):
    registration = get_object_or_404(Registration, pk=registration_id)
    registration.status = 3
    registration.save()
    return redirect('/doctor/registrations')

def medicine(request):
    medicines = Medicine.objects.all()
    types = Medicine.TYPE_CHOICES

    # 获取查询值
    name_query = request.GET.get('name', '')
    type_query = request.GET.get('type', '')
    
    if name_query:
        medicines = medicines.filter(name__contains=name_query)
    
    if type_query:
        medicines = medicines.filter(type=type_query)
    
    # 分页
    paginator = Paginator(medicines, 10)
    page_number = request.GET.get('page')
    medicines = paginator.get_page(page_number)

    # 转换为int在前端进行比较
    type_query = int(type_query, base=10) if type_query != '' else type_query
    print(type_query)
    
    return render(request, 'doctor/medicine.html', {'medicines': medicines, 'name_query': name_query, 'type_query': (type_query), 'types' : types})

def personal(request):
    doctor_id = request.session.get('info')['id']
    doctor = Doctor.objects.get(id=doctor_id)
    return render(request, 'doctor/personal.html', {'doctor': doctor})

hospital/views/login.py
from django.shortcuts import render, redirect, get_object_or_404

from hospital.models import Patient, Doctor
from django import forms
from django.core.validators import ValidationError

class LoginForm(forms.Form):
    username = forms.fields.CharField(
        required=True,
        # min_length=3,
        # max_length=16,
        label="用户名",
        widget=forms.widgets.TextInput({"placeholder":"请输入用户名","class":"form-control"})
    )
    password = forms.fields.CharField(
        required=True,
        # min_length=3,
        # max_length=16,
        label="密码",
        widget=forms.widgets.PasswordInput({"placeholder":"请输入密码","class":"form-control"})
    )

    # def clean_username(self):
    #     username = self.cleaned_data["username"]
    #     is_exits = Patient.objects.filter(username=username).count()
    #     if not is_exits:
    #         raise ValidationError("用户名不存在")
    #     return user

def login(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request, "login/login.html", {"form": form})
    
    form = LoginForm(data=request.POST)
    if form.is_valid():
        print(form.cleaned_data)
        login_type = request.POST.get('login_type')
        print(login_type)
        user_model = Patient if login_type == 'patient_login' else Doctor
        user = user_model.objects.filter(**form.cleaned_data).first()

        if user:
            # 验证成功，跳转到主页
            print(user.username)
            request.session["info"] = {'id': user.id, 'login_type': login_type}
            if login_type == 'patient_login':
                return redirect("/patient/home/")
            else:
                return redirect("/doctor/home/")    
        else:
            # 验证失败，增加错误并重新渲染
            form.add_error("password", "用户名或密码不正确")
            return render(request, "login/login.html", {"form": form})
    
    return render(request, "login/login.html", {"form": form})


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['name', 'age', 'username', 'password', 'gender']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def clean_username(self):
        username = self.cleaned_data['username']
        # 检查数据库中是否已经存在相同的用户名
        if Patient.objects.filter(username=username).exists():
            raise ValidationError("该用户名已被使用，请重新填写")
        return username
    
    def __init__(self, *args, **kwargs):
        super(PatientForm, self).__init__(*args, **kwargs)
        self.fields['name'].required = True
        self.fields['username'].required = True
        self.fields['password'].required = True

def enroll(request):
    if request.method == 'POST':
        form = PatientForm(request.POST)
        if form.is_valid():
            patient = form.save()
            return redirect('/login/')
    else:
        form = PatientForm()
    
    return render(request, "login/enroll.html", {"form": form})

def logout(request):
    request.session.clear()
    return redirect('/login/')

hospital/views/patient.py
from django.shortcuts import render, redirect, get_object_or_404

from hospital.models import *
from datetime import datetime
from django.core.paginator import Paginator

def home(request):
    return render(request, 'patient/home.html')

def register(request):
    doctors = Doctor.objects.all()
    departments = Department.objects.all()

    # 获取查询值
    name_query = request.GET.get('name', '')
    dept_query = request.GET.get('department', '')
    
    if name_query:
        doctors = doctors.filter(name__contains=name_query)
    
    if dept_query:
        doctors = doctors.filter(dept=dept_query)

    # 分页
    paginator = Paginator(doctors, 10)
    page_number = request.GET.get('page')
    doctors = paginator.get_page(page_number)

    # 转换为int在前端进行比较
    dept_query = int(dept_query, base=10) if dept_query != '' else dept_query
    
    return render(request, 'patient/register.html', {'doctors': doctors, 'name_query': name_query, 'dept_query': (dept_query), 'departments' : departments})
    
def register_sucess(request):
    return render(request, 'patient/register_success.html')

def register_appoint(request, doctor_id):
    doctor = get_object_or_404(Doctor, pk=doctor_id)

    if request.method == 'POST':
        appointment_time = request.POST.get('appointment_time')
        period = request.POST.get('period')

        # 将字符串时间转换为datetime对象
        appointment_datetime = datetime.strptime(appointment_time, '%Y-%m-%d')

        # 通过session获得病人实例
        patient = Patient.objects.get(id=request.session.get('info')['id'])

        # 创建挂号记录
        registration = Registration.objects.create(
            doctor=doctor,
            patient=patient,
            registration_time=appointment_datetime,
            period=period,
            status=0,
        )

        return redirect('/patient/register/success/')

    options = Registration.PERIOD_CHOICES
    return render(request, 'patient/register_appoint.html', {'doctor': doctor, 'options': options})

def register_appoint_test(request):
    return render(request, 'patient/register_appoint.html')

def registrations(request):
    patient_id = request.session.get('info')['id']
    patient = Patient.objects.get(id=patient_id)
    registrations = Registration.objects.filter(patient=patient)

    # 分页
    paginator = Paginator(registrations, 10)
    page_number = request.GET.get('page')
    registrations = paginator.get_page(page_number)

    return render(request, 'patient/registrations.html', {'registrations':registrations})

def cancel_registration(request, registration_id):
    registration = get_object_or_404(Registration, pk=registration_id)
    if registration.status == 0:
        registration.status = 1
        registration.save()
    
    return redirect('/patient/registrations/')


def personnel(request):
    doctors = Doctor.objects.all()
    departments = Department.objects.all()
    return render(request, 'patient/personnel.html', {'doctors': doctors, 'departments': departments})

def profile(request, doctor_id):
    doctor = get_object_or_404(Doctor, pk=doctor_id)
    return render(request, 'patient/profile.html', {'doctor': doctor})

def medical_record(request, registration_id):
    registration = get_object_or_404(Registration, pk=registration_id)
    medical_record = MedicalRecord.objects.get(registration=registration)
    return render(request, 'patient/medical_record.html', {'medical_record': medical_record})

def personal(request):
    patient_id = request.session.get('info')['id']
    patient = Patient.objects.get(id=patient_id)
    return render(request, 'patient/personal.html', {'patient': patient})

def mytest(request):
    # patient_list = Patient.objects.all()
    mylist = [1,2,3,4,5,6,7,8,9,10]
    paginator = Paginator(mylist, 2)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'test.html', {'page_obj': page_obj})

hospital/templates/enroll.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient Registration</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }
    
        form {
            background-color: #fff;
            padding: 30px;  /* Increase padding for the entire form */
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
    
        h2 {
            text-align: center;
            color: #333;
        }
    
        label {
            display: block;
            margin-bottom: 8px;
            color: #555;
        }
    
        select {
        width: 90%;  /* 设置所有输入框和选择框的宽度为100% */
        padding: 10px;
        margin-bottom: 16px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 4px;
        }

        input {
            width: calc(100% - 20px);  /* Adjust width of input to accommodate padding */
            padding: 10px;
            margin-bottom: 20px;  /* Increase margin between input fields */
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
    
        input[type="submit"] {
            margin-top: 15px;
            background-color: #4caf50;
            color: white;
            cursor: pointer;
        }
    
        input[type="submit"]:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>

<form method="post">
    {% csrf_token %}
    <h2>Patient Registration</h2>

    <label for="id_name">Name:</label>
    {{ form.name }}

    <label for="id_username">Username:</label>
    {{ form.username }}

    <label for="id_password">Password:</label>
    {{ form.password }}

    <label for="id_age">Age:</label>
    {{ form.age }}

    <label for="id_gender">Gender:</label>
    {{ form.gender }}

    <input type="submit" value="Register">
</form>

</body>
</html>

hospital/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>医院主页</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f8f8f8;
        }

        header {
            background-color: #3498db;
            color: #fff;
            padding: 20px;
            text-align: center;
        }

        nav {
            background-color: #333;
            overflow: hidden;
        }

        nav a {
            float: left;
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            transition: background-color 0.3s;
        }

        nav a:hover {
            background-color: #ddd;
            color: black;
        }

        section {
            padding: 40px;
            text-align: center;
        }

        section h2 {
            color: #333;
        }

        section p {
            color: #555;
            font-size: 1.2em;
            line-height: 1.6em;
        }

        footer {
            background-color: #333;
            color: #fff;
            text-align: center;
            padding: 10px;
            position: fixed;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>
<body>

    <header>
        <h1>医院名称</h1>
    </header>

    <nav>
        <a href="#home">首页</a>
        <a href="/patient_personal">个人中心</a>
        <a href="/register">预约挂号</a>
    </nav>

    <section>
        <h2>欢迎访问医院主页</h2>
        <p>我们致力于为患者提供高质量的医疗服务，关心您的健康。通过专业的医生团队和先进的医疗设施，我们竭诚为您服务。</p>
        <p>在这里，我们不仅提供全面的医疗服务，还致力于预防和健康教育。我们的目标是让每一位患者都能够获得最佳的医疗体验。</p>
    </section>

    <footer>
        <p>&copy; 2023 医院名称. All rights reserved.</p>
    </footer>

</body>
</html>

hospital/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login Page</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      background-color: #f8f9fa;
      margin: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      height: 100vh;
    }

    .container {
      background-color: #fff;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      padding: 20px;
      text-align: center;
    }

    .form-container {
      width: 300px;
      margin: 0 auto;
    }

    .form-group {
      margin-bottom: 15px;
      margin-top: 15px;
    }

    .form-control {
      width: 100%;
      padding: 10px;
      box-sizing: border-box;
      border: 1px solid #ced4da;
      border-radius: 4px;
      margin-bottom: 10px;
    }

    .btn-container {
      display: flex;
      justify-content: space-between;
    }

    .btn {
      width: 48%;
      padding: 10px;
      box-sizing: border-box;
      cursor: pointer;
      border: none;
      border-radius: 4px;
    }

    .btn-primary {
      background-color: #007bff;
      color: #fff;
    }

    .btn-success {
      background-color: #28a745;
      color: #fff;
    }

    .btn-register {
      text-decoration: none; /* 去除下划线 */
      width: 100%;
      padding: 10px;
      box-sizing: border-box;
      cursor: pointer;
      background-color: #17a2b8;
      color: #fff;
      border: none;
      border-radius: 4px;
    }
  </style>
</head>

<body>
  <div class="container">
    <div class="form-container">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="btn-container">
          <button type="submit" name="login_type" value="doctor_login" class="btn btn-primary">医生登录</button>
          <button type="submit" name="login_type" value="patient_login" class="btn btn-success">患者登录</button>
        </div>
      </form>
      <div class="form-group">
        <a href="" class="btn-register">患者注册</a>
      </div>
    </div>
  </div>
</body>

</html>

hospital/templates/patient_personal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>挂号记录</title>
  <link rel="stylesheet" href="{% static 'css/patient.css' %}">
</head>
<body>

  <h1>挂号记录</h1>


  <!-- 患者挂号记录表格 -->
  <table>
    <thead>
      <tr>
        <th>医生姓名</th>
        <th>挂号时间</th>
        <th>挂号时段</th>
        <th>状态</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      {% for registration in registrations %}
      <tr>
        <td>{{ registration.doctor.name }}</td>
        <td>{{ registration.resgitration_time }}</td>
        <td>{{ registration.peirod }}</td>
        <td>{{ registration.status }}</td>
        {% if registration.status == 'registered' %}
        <td><a href="{% url 'cancel_registration' registration.id %}">取消预约</a></td>
        {%endif%}
      </tr>
      {% endfor %}
    </tbody>
  </table>

</body>
</html>

hospital/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>医生列表</title>
  <link rel="stylesheet" href="{% static 'css/register.css' %}">
</head>
<body>

  <h1>医生列表</h1>

  <!-- 搜索栏 -->
  <form method="get" action="/register/">
    <label for="name">医生姓名：</label>
    <input type="text" id="name" name="name" value="{{ name_query }}">
    <label for="department">科室：</label>
    <input type="text" id="department" name="department" value="{{ dept_query }}">
    <button type="submit">搜索</button>
  </form>

  <!-- 医生列表表格 -->
  <table>
    <thead>
      <tr>
        <th>医生姓名</th>
        <th>科室</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      {% for doctor in doctors_data %}
      <tr>
        <td>{{ doctor.name }}</td>
        <td>{{ doctor.dept.name }}</td>
        <td><a href="/register/appoint/{{ doctor.id }}/">预约</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

</body>
</html>

hospital/templates/register_appoint.html
{% load static %}
<!-- doctors_list.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>医生列表</title>
</head>
<body>

  <h1>医生列表</h1>

  <!-- 搜索栏 -->
  <form method="post">
    <!-- 使用HTML5日期选择器 -->
    <label for="appointment_time">选择日期：</label>
    <input type="date" id="appointment_time" name="appointment_time">

    <!-- 时段选择 -->
    {% csrf_token %}
    <label for="period">选择时段：</label>
    <select id="period" name="period">
      {% for k,v in options %}
      <option value="{{k}}">{{v}}</option>
      {%endfor%}
    </select>

    <button type="submit">提交预约</button>
  </form>

</body>
</html>