connect_db/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView
from hospital.views import patient, doctor, login

urlpatterns = [
    #path('', RedirectView.as_view(url='/login/', permanent=True), name='index'),
    # 其他URL模式
    path("admin/", admin.site.urls),
    path("login/", login.login),
    path("enroll/", login.enroll),
    path("logout/", login.logout),
    
    path("patient/home/", patient.home),
    path("patient/register/", patient.register),
    path("patient/register/appoint/<int:doctor_id>/", patient.register_appoint),
    path("patient/register/success/", patient.register_sucess),
    path("patient/register/appoint/", patient.register_appoint_test),
    path("patient/registrations/", patient.registrations),
    path("patient/cancel_registration/<int:registration_id>/", patient.cancel_registration),
    path("patient/personnel/", patient.personnel),
    path("patient/profile/<int:doctor_id>/", patient.profile),
    path('patient/medical_record/<int:registration_id>/', patient.medical_record),
    path('patient/personal/', patient.personal),
    path("mytest/", patient.mytest),

    path('doctor/home/', doctor.home),
    path('doctor/registrations/', doctor.registrations),
    path('doctor/medical_record/<int:registration_id>/', doctor.medical_record),
    path('doctor/accept/<int:registration_id>/', doctor.accept),
    path('doctor/finish/<int:registration_id>/', doctor.finish),
    path('doctor/medicine/', doctor.medicine),
    path('doctor/personal/', doctor.personal),
]

hospital/models.py
from django.db import models

class Patient(models.Model):
    '''病人'''
    name = models.CharField(verbose_name='姓名', max_length = 20)
    age = models.IntegerField(verbose_name='年龄', null=True, blank=True)
    username = models.CharField(verbose_name='用户名', max_length = 20, unique=True)
    password = models.CharField(verbose_name='密码', max_length = 20)
    GENDER_CHOICES = [
        (0, '男'),
        (1, '女'),
    ]
    gender = models.SmallIntegerField(verbose_name='性别', choices=GENDER_CHOICES, null=True, blank=True)

class Department(models.Model):
    '''科室'''
    name = models.CharField(verbose_name='科室名', max_length = 30)
    room_number = models.CharField(verbose_name='房间号', max_length = 20)

class Doctor(models.Model):
    '''医生'''
    name = models.CharField(verbose_name='姓名', max_length = 20)
    username = models.CharField(verbose_name='用户名', max_length = 20, unique=True)
    password = models.CharField(verbose_name='密码', max_length = 20)
    title = models.CharField(verbose_name='职称', max_length = 20)
    dept = models.ForeignKey(Department, verbose_name='科室', on_delete=models.CASCADE)
    profile = models.CharField(verbose_name='简介', max_length = 200)


class Registration(models.Model):
    '''挂号记录'''

    # class Meta:
    #     verbose_name = '挂号记录'
    #     verbose_name_plural = '挂号记录'

    STATUS_CHOICES = [
        (0, '已挂号'),
        (1, '已取消'),
        (2, '就诊中'),
        (3, '就诊结束'),
    ]

    PERIOD_CHOICES = [
        (0, '8:00-10:00'),
        (1, '10:00-12:00'),
        (2, '14:00-16:00'),
        (3, '16:00-18:00'),
    ]

    doctor = models.ForeignKey(Doctor, verbose_name='医生', on_delete=models.CASCADE, related_name='registrations')
    patient = models.ForeignKey(Patient, verbose_name='患者', on_delete=models.CASCADE, related_name='appointments')
    registration_time = models.DateTimeField(verbose_name='挂号时间')
    period = models.SmallIntegerField(verbose_name='挂号时段', choices=PERIOD_CHOICES)
    status = models.SmallIntegerField(verbose_name='状态', choices=STATUS_CHOICES)

class MedicalRecord(models.Model):
    '''病历'''
    symptom = models.CharField(verbose_name='症状', max_length = 2000)
    diagnosis = models.CharField(verbose_name='诊断结果', max_length = 2000)
    solution = models.CharField(verbose_name='治疗方案', max_length = 2000)
    registration = models.ForeignKey(Registration, verbose_name='预约信息', on_delete=models.CASCADE)


class Medicine(models.Model):
    '''药物'''
    TYPE_CHOICES = [
        (0, '中药'),
        (1, '西药'),
    ]

    name = models.CharField(verbose_name='名称', max_length = 100)
    type = models.SmallIntegerField(verbose_name='类型', choices=TYPE_CHOICES)
    producer = models.CharField(verbose_name='生产厂商', max_length = 100)
    price = models.DecimalField(verbose_name='价格', max_digits=5, decimal_places=2)

hospital/views/doctor.py
from django.shortcuts import render, redirect, get_object_or_404
from hospital.models import *
from django import forms
from django.core.paginator import Paginator

def home(request):
    return render(request, 'doctor/home.html')

def registrations(request):
    doctor_id = request.session.get('info')['id']
    doctor = Doctor.objects.get(id=doctor_id)
    registrations = Registration.objects.filter(doctor=doctor).order_by('registration_time', 'period')


    # 分页
    paginator = Paginator(registrations, 5)
    page_number = request.GET.get('page')
    registrations = paginator.get_page(page_number)

    return render(request, 'doctor/registrations.html', {'registrations': registrations})

class MedicalRecordForm(forms.ModelForm):
    class Meta:
        model = MedicalRecord
        exclude = ['registration']

def medical_record(request, registration_id):
    registration = get_object_or_404(Registration, pk=registration_id)
    
    try:
        medical_record = MedicalRecord.objects.get(registration=registration)
    except MedicalRecord.DoesNotExist:
        medical_record = None

    patient = registration.patient

    if request.method == 'GET':
        if medical_record == None:
            form = None
        else:
            form = MedicalRecordForm(instance=medical_record)
        return render(request, 'doctor/medical_record.html', {'form': form, 'patient': patient})

    form = MedicalRecordForm(request.POST, instance=medical_record)
    if form.is_valid():
        medical_record = form.save(commit=False)
        medical_record.registration = registration
        medical_record.save()
    return render(request, 'doctor/medical_record.html', {'form': form, 'patient': patient})
    
def accept(request, registration_id):
    registration = get_object_or_404(Registration, pk=registration_id)
    registration.status = 2
    registration.save()
    print('accept', registration_id)
    return redirect('/doctor/registrations')

def finish(request, registration_id):
    registration = get_object_or_404(Registration, pk=registration_id)
    registration.status = 3
    registration.save()
    return redirect('/doctor/registrations')

def medicine(request):
    medicines = Medicine.objects.all()
    types = Medicine.TYPE_CHOICES

    # 获取查询值
    name_query = request.GET.get('name', '')
    type_query = request.GET.get('type', '')
    
    if name_query:
        medicines = medicines.filter(name__contains=name_query)
    
    if type_query:
        medicines = medicines.filter(type=type_query)
    
    # 分页
    paginator = Paginator(medicines, 10)
    page_number = request.GET.get('page')
    medicines = paginator.get_page(page_number)

    # 转换为int在前端进行比较
    type_query = int(type_query, base=10) if type_query != '' else type_query
    print(type_query)
    
    return render(request, 'doctor/medicine.html', {'medicines': medicines, 'name_query': name_query, 'type_query': (type_query), 'types' : types})

def personal(request):
    doctor_id = request.session.get('info')['id']
    doctor = Doctor.objects.get(id=doctor_id)
    return render(request, 'doctor/personal.html', {'doctor': doctor})

hospital/views/login.py
from django.shortcuts import render, redirect, get_object_or_404

from hospital.models import Patient, Doctor
from django import forms
from django.core.validators import ValidationError

class LoginForm(forms.Form):
    username = forms.fields.CharField(
        required=True,
        # min_length=3,
        # max_length=16,
        label="用户名",
        widget=forms.widgets.TextInput({"placeholder":"请输入用户名","class":"form-control"})
    )
    password = forms.fields.CharField(
        required=True,
        # min_length=3,
        # max_length=16,
        label="密码",
        widget=forms.widgets.PasswordInput({"placeholder":"请输入密码","class":"form-control"})
    )

    # def clean_username(self):
    #     username = self.cleaned_data["username"]
    #     is_exits = Patient.objects.filter(username=username).count()
    #     if not is_exits:
    #         raise ValidationError("用户名不存在")
    #     return user

def login(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request, "login/login.html", {"form": form})
    
    form = LoginForm(data=request.POST)
    if form.is_valid():
        print(form.cleaned_data)
        login_type = request.POST.get('login_type')
        print(login_type)
        user_model = Patient if login_type == 'patient_login' else Doctor
        user = user_model.objects.filter(**form.cleaned_data).first()

        if user:
            # 验证成功，跳转到主页
            print(user.username)
            request.session["info"] = {'id': user.id, 'login_type': login_type}
            if login_type == 'patient_login':
                return redirect("/patient/home/")
            else:
                return redirect("/doctor/home/")    
        else:
            # 验证失败，增加错误并重新渲染
            form.add_error("password", "用户名或密码不正确")
            return render(request, "login/login.html", {"form": form})
    
    return render(request, "login/login.html", {"form": form})


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['name', 'age', 'username', 'password', 'gender']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def clean_username(self):
        username = self.cleaned_data['username']
        # 检查数据库中是否已经存在相同的用户名
        if Patient.objects.filter(username=username).exists():
            raise ValidationError("该用户名已被使用，请重新填写")
        return username
    
    def __init__(self, *args, **kwargs):
        super(PatientForm, self).__init__(*args, **kwargs)
        self.fields['name'].required = True
        self.fields['username'].required = True
        self.fields['password'].required = True

def enroll(request):
    if request.method == 'POST':
        form = PatientForm(request.POST)
        if form.is_valid():
            patient = form.save()
            return redirect('/login/')
    else:
        form = PatientForm()
    
    return render(request, "login/enroll.html", {"form": form})

def logout(request):
    request.session.clear()
    return redirect('/login/')

hospital/views/patient.py
from django.shortcuts import render, redirect, get_object_or_404

from hospital.models import *
from datetime import datetime
from django.core.paginator import Paginator

def home(request):
    return render(request, 'patient/home.html')

def register(request):
    doctors = Doctor.objects.all()
    departments = Department.objects.all()

    # 获取查询值
    name_query = request.GET.get('name', '')
    dept_query = request.GET.get('department', '')
    
    if name_query:
        doctors = doctors.filter(name__contains=name_query)
    
    if dept_query:
        doctors = doctors.filter(dept=dept_query)

    # 分页
    paginator = Paginator(doctors, 10)
    page_number = request.GET.get('page')
    doctors = paginator.get_page(page_number)

    # 转换为int在前端进行比较
    dept_query = int(dept_query, base=10) if dept_query != '' else dept_query
    
    return render(request, 'patient/register.html', {'doctors': doctors, 'name_query': name_query, 'dept_query': (dept_query), 'departments' : departments})
    
def register_sucess(request):
    return render(request, 'patient/register_success.html')

def register_appoint(request, doctor_id):
    doctor = get_object_or_404(Doctor, pk=doctor_id)

    if request.method == 'POST':
        appointment_time = request.POST.get('appointment_time')
        period = request.POST.get('period')

        # 将字符串时间转换为datetime对象
        appointment_datetime = datetime.strptime(appointment_time, '%Y-%m-%d')

        # 通过session获得病人实例
        patient = Patient.objects.get(id=request.session.get('info')['id'])

        # 创建挂号记录
        registration = Registration.objects.create(
            doctor=doctor,
            patient=patient,
            registration_time=appointment_datetime,
            period=period,
            status=0,
        )

        return redirect('/patient/register/success/')

    options = Registration.PERIOD_CHOICES
    return render(request, 'patient/register_appoint.html', {'doctor': doctor, 'options': options})

def register_appoint_test(request):
    return render(request, 'patient/register_appoint.html')

def registrations(request):
    patient_id = request.session.get('info')['id']
    patient = Patient.objects.get(id=patient_id)
    registrations = Registration.objects.filter(patient=patient)

    # 分页
    paginator = Paginator(registrations, 10)
    page_number = request.GET.get('page')
    registrations = paginator.get_page(page_number)

    return render(request, 'patient/registrations.html', {'registrations':registrations})

def cancel_registration(request, registration_id):
    registration = get_object_or_404(Registration, pk=registration_id)
    if registration.status == 0:
        registration.status = 1
        registration.save()
    
    return redirect('/patient/registrations/')


def personnel(request):
    doctors = Doctor.objects.all()
    departments = Department.objects.all()
    return render(request, 'patient/personnel.html', {'doctors': doctors, 'departments': departments})

def profile(request, doctor_id):
    doctor = get_object_or_404(Doctor, pk=doctor_id)
    return render(request, 'patient/profile.html', {'doctor': doctor})

def medical_record(request, registration_id):
    registration = get_object_or_404(Registration, pk=registration_id)
    medical_record = MedicalRecord.objects.get(registration=registration)
    return render(request, 'patient/medical_record.html', {'medical_record': medical_record})

def personal(request):
    patient_id = request.session.get('info')['id']
    patient = Patient.objects.get(id=patient_id)
    return render(request, 'patient/personal.html', {'patient': patient})

def mytest(request):
    # patient_list = Patient.objects.all()
    mylist = [1,2,3,4,5,6,7,8,9,10]
    paginator = Paginator(mylist, 2)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'test.html', {'page_obj': page_obj})

hospital/templates/doctor/medical_record.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>病例详情</title>

  <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css'%}"/>


 

  <style>
    body {
        overflow: hidden;
        background-color: aliceblue;
        color: #333;
        font-family: 'Arial', sans-serif;
        padding: 0;

    }

    /* 调整输入框的大小 */
    table textarea {
        width: 100%;
        height: 100px; /* 调整输入框的高度 */
    }

    .btn-primary {
        background-color: #a5bdd4;
        border-color: #a5bdd4;
        color: #fff;
        padding: 8px 12px;
        border-radius: 6px;
        cursor: pointer;
    }

    .btn-primary:hover {
        background-color: #112434;
        border-color: #112434;
    }

    table {
        width: 70%; /* 设置表格宽度为页面宽度的80% */
        margin: auto; /* 设置左右外边距为 auto，实现水平居中 */
        border-collapse: collapse; /* 合并单元格边框 */
    }

    th, td {
        padding: 15px; /* 设置单元格内边距 */
        text-align: center; /* 文字水平居中 */
        border: 1px solid #ddd;
        
    }

    th {
        font-size: 16px; /* 调整表头字体大小 */
        background-color: #112434;
        color: #fff;
    }
    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
    .error {
        color: #dc3545;
        font-size: 95%;
    }

    .name {
        font-size: 125%;
    }
    .return-link {
        position: fixed;
        top: 10px;
        right: 10px;
        margin-right: 40px;
        margin-top: 20px;
        text-decoration: underline;
        font-size: 1.2em; /* 调整字体大小 */
        color: #112434;
    }
    h1 {
        text-align: center;
        color: #112434;
    }

  </style>
</head>
<body>
  <h1>填写病历</h1>
  <a href="/doctor/registrations" class="return-link">返回上一页</a>

  <form method="post" style="margin-top: 30px;">
    {% csrf_token %}
    <table>
        <tbody>
            <tr>
                <th style="width:100px;">患者姓名</th>
                <td>
                  <span class="name">{{ patient.name }}</span>
                </td>
            </tr>
            <tr>
                <th style="width:100px;">症状</th>
                <td>
                    <textarea name="symptom">{{ form.symptom.value }}</textarea>
                    <span class="error">{{ form.symptom.errors.0 }}</span>
                </td>
            </tr>
            <tr>
                <th style="width:100px;">诊断结果</th>
                <td>
                    <textarea name="diagnosis">{{ form.diagnosis.value }}</textarea>
                    <span class="error">{{ form.diagnosis.errors.0 }}</span>
                </td>
            </tr>
            <tr>
                <th style="width:100px;">治疗方案</th>
                <td>
                    <textarea name="solution">{{ form.solution.value }}</textarea>
                    <span class="error">{{ form.solution.errors.0 }}</span>
                </td>
            </tr>
            <tr>
                <th style="width:100px;"></th>
                <td><button type="submit" class="btn btn-primary">保存</button></td>
            </tr>
        </tbody>
    </table>
</form>
</body>
</html>

hospital/templates/doctor/medicine.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>医生界面 - 药房</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css'%}">
        <link rel="stylesheet" href="{% static 'css/bootstrap/font-awesome.min.css'%}"/>
        <link rel="stylesheet" href="{% static 'css/doctor/medicine.css'%}">

    </head>

<body>
    <!-- 菜单栏和页面内容容器 -->
    <div class="menu-container">
        <!-- 菜单栏 -->
        <div class="sidenav" style="bottom:0;">
            <h5 style="color: #fff; margin: 30px; margin-top: 10px;">医生界面</h5>
            <a href="/doctor/home">首页</a>
            <a href="/doctor/registrations">患者预约记录</a>  
            <a href="#"  class="active">药房</a>
            <a href="/doctor/personal">个人中心</a>
        </div>
    </div>
    
        
        <div class="container" style="margin-top: 23px;">
            <form  method="get">
                <label for="name" style=" font-weight: bold;">药物名：</label>
                <input type="text" id="name" name="name" value="{{ name_query }}" style="margin-right: 10px;">
                
                <label for="type" style=" font-weight: bold;">类型：</label>
                <select id="type" name="type">
                    <option value="" {% if not type_query %}selected{% endif %} style="color: #999;">选择类型</option>
                    {% for type in types %}
                        <option value="{{ type.0 }}" {% if type.0 == type_query %}selected{% endif %}>
                            {{ type.1 }}
                        </option>
                    {% endfor %}
                </select>        
                
                <button type="submit" class="btn btn-primary">搜索</button>
              </form>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col" >药物名</th>
                    <th scope="col" >类型</th>
                    <th scope="col" >生产厂商</th>
                    <th scope="col" >价格</th>      
                </tr>
                </thead>
                <tbody>
                    {% for medicine in medicines %}
                    <tr>
                        <td>{{ medicine.name }}</td>
                        <td>{{ medicine.get_type_display }}</td>
                        <td>{{medicine.producer}}</td>
                        <td>{{ medicine.price }}￥</td>
                    </tr>
                    {% endfor %}
                    </tbody>
            </table>
            
            <div class="pagination">
                <span class="step-links">
                    {% if medicines.has_previous %}
                        <a href="?page=1">&laquo; 首页</a>
                        <a href="?page={{ medicines.previous_page_number }}">上一页</a>
                    {% else %}
                    <a>&laquo; 首页</a>
                    <a>上一页</a>
                    {% endif %}
            
                    <span class="current">
                        第 {{ medicines.number }} / {{ medicines.paginator.num_pages }} 页
                    </span>
            
                    {% if medicines.has_next %}
                        <a href="?page={{ medicines.next_page_number }}">下一页</a>
                        <a href="?page={{ medicines.paginator.num_pages }}">尾页 &raquo;</a>
                    {% else %}
                    <a>下一页</a>
                    <a>尾页 &raquo;</a>                    
                    {% endif %}
                </span>
            </div>
        </body>
        
    </div>
    </div>  
        
</body>
</html>

hospital/templates/doctor/registrations.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>医生界面 - 患者预约记录</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/bootstrap/menu.css'%}">

<style>
    h2 {
        margin: 20px;
        text-align: center;
        margin-bottom: 0px;
    }
    th {
        text-align: center;
        vertical-align: middle; /* 垂直居中 */
    }
    .table {
        table-layout: fixed;
        vertical-align: middle; /* 垂直居中 */
        
    }
    /* 设置表头的样式 */
    .table thead {
        position: sticky;
        top: 0; /* 保持在顶部 */
        background-color: #f8f9fa; /* 背景色 */
        z-index: 1; /* 确保在内容之上 */
        
    }

    /* 设置医生姓名、科室、操作列的样式 */
    .table th {
        background-color: #f8f9fa; /* 背景色 */
        position: sticky;
        top: 0; /* 保持在顶部 */
        z-index: 2; /* 确保在内容之上 */
        width: 100px; /* 固定宽度 */
        text-overflow: ellipsis; /* 显示省略号 */
        vertical-align: middle; /* 垂直居中 */
    }

    /* 将表项居中对齐 */
    .table td {
        text-align: center;
        vertical-align: middle; /* 垂直居中 */
        font-size: 18px;
    }

    /* 居中预约按钮 */
    .table button {
        margin: 0 auto;
        display: block;
    }

    .pagination {
        position: absolute;
        bottom: 10px;
        left: 50%;
        transform: translateX(-50%);
    }

    .step-links {
        display: flex;
        align-items: center;
        white-space: nowrap;
        line-height: 1;
        margin-bottom: 20px;
    }

    .step-links a {
        text-decoration: none;
        padding: 8px 10px;
        border: 2px solid #a5bdd4;
        border-radius: 6px;
        color: #333;
        transition: background-color 0.3s;
        display: inline-block; /* 让链接元素显示为行内块级元素 */
        margin-right: 5px; /* 调整链接之间的右边距 */
    }

    .step-links a:hover {
        background-color: #a5bdd4;
        color: #fff;
    }

    .current {
        padding: 8px 12px;
        background-color: #a5bdd4;
        color: #fff;
        border: 2px solid #a5bdd4;
        border-radius: 6px;
        margin: 0 5px;
    }

    .action-buttons {
        display: flex;
        justify-content: space-around;

    }

    button {
        display: flex;
        flex-direction: row;
        align-items: center; /* 垂直居中对齐 */
        justify-content: center;
        padding: 10px;
        font-size: 20px;
        cursor: pointer;    
        margin-right: 10px;   
    }
    .btn-able{
        
        background-color: #4caf50;
        color: #fff;
        margin-right: 10px;
    }
    .btn-disable {
        background-color: #ccc;
        color: #fff;
        cursor: not-allowed;       
    }
    .btn-able:hover {
        background-color: #a5bdd4; /* 鼠标悬停时的背景颜色 */
        border-color: #a5bdd4; /* 鼠标悬停时的边框颜色 */
        color: #112434;   
    }
</style>
</head>

<body>
    <!-- 菜单栏和页面内容容器 -->
    <div class="menu-container">
        <!-- 菜单栏 -->
        <div class="sidenav"> 
            <h5 style="color: #fff; margin: 30px; margin-top: 10px;">医生界面</h5>
            <a href="/doctor/home">首页</a>
            <a href="#" class="active">患者预约记录</a>  
            <a href="/doctor/medicine">药房</a>
        </div>
    </div>

    <div class="container" style="margin-top: 23px; overflow: hidden;">
            <h2 style="margin-bottom: 20px;">患者预约记录</h2>
    
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">患者姓名</th>
                        <th scope="col">预约时间</th>
                        <th scope="col">预约时段</th> 
                        <th scope="col">状态</th> 
                        <th scope="col">操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for registration in registrations %}
                    <tr>
                        <td>{{ registration.patient.name }}</td>
                        <td>{{ registration.registration_time|date:"Y 年 m 月 d 日"}}</td>
                        <td>{{ registration.get_period_display }}</td>
                        <td>{{ registration.get_status_display }}</td>
                        <td>
                            <div class="action-buttons">
                                {% if registration.status == 0 %}
                                <button class="btn btn-able" style=" margin-right: 5px; margin-left: -35px;" onclick="acceptAppointment(this, {{ registration.id}})">接诊</button>   
                                {% else %}
                                    <button class="btn btn-disable" style=" margin-right: 5px; margin-left: -35px;">接诊</button>
                                {% endif %}
    
                                {% if registration.status == 2 %}
                                    <button class="btn btn-able" style="margin-right: 5px;" onclick="fillCase(this, {{ registration.id}})">填写病例</button>
                                {% else %}
                                    <button class="btn btn-disable" style="margin-right: 5px;">填写病例</button>
                                {% endif %}
    
                                {% if registration.status == 2 %}
                                <button class="btn btn-able" style="margin-right: 5px;" onclick="endVisit(this, {{ registration.id}})">结束就诊</button>
                                {% else %}
                                    <button class="btn btn-disable" style="margin-right: 5px;">结束就诊</button>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                    {% endfor %}                       
                </tbody>
            </table>
            <div class="pagination">
                <span class="step-links">
                    {% if registrations.has_previous %}
                        <a href="?page=1">&laquo; 首页</a>
                        <a href="?page={{ registrations.previous_page_number }}">上一页</a>
                    {% else %}
                    <a>&laquo; 首页</a>
                    <a>上一页</a>
                    {% endif %}
            
                    <span class="current">
                        第 {{ registrations.number }} / {{ registrations.paginator.num_pages }} 页
                    </span>
            
                    {% if registrations.has_next %}
                        <a href="?page={{ registrations.next_page_number }}">下一页</a>
                        <a href="?page={{ registrations.paginator.num_pages }}">尾页 &raquo;</a>
                    {% else %}
                    <a>下一页</a>
                    <a>尾页 &raquo;</a>                    
                    {% endif %}
                </span>
            </div>
        </div>
        
    
        <script>
            function acceptAppointment(btn, registrationID) {
                alert('接诊成功！');
                window.location.href = '/doctor/accept/'+registrationID;
            }
    
            function fillCase(btn, registrationID) {
                window.location.href = '/doctor/medical_record/'+registrationID;
            }
    
            function endVisit(btn, registrationID) {
                alert('就诊结束！');
                window.location.href = '/doctor/finish/'+registrationID;
            }
        </script>
    </body>
    
    </html>